/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ui.quickfix;

import org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class XawQuickfixProvider extends XbaseWithAnnotationsQuickfixProvider {
}
