/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ui.contentassist;

import etablesaw.xtext.ui.contentassist.AbstractXawProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XawProposalProvider extends AbstractXawProposalProvider {
}
