/*
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractXawScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
