/*
 * generated by Xtext 2.12.0
 */
package etablesaw.xtext.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.Test
import org.junit.runner.RunWith
import etablesaw.xtext.xaw.Xaw

@RunWith(XtextRunner)
@InjectWith(XawInjectorProvider)
class XawParsingTest {
	
	@Inject extension ValidationTestHelper

	@Inject extension ParseHelper<Xaw>	
	
	@Test
	def void loadModel() {
		parse('''
		xaw etablesaw.xtext.tests.LoadModelTest
		val halAge = 52.0
		val table1 =
		# String name, double age #
		| "Hallvard", halAge |
		def String helper1(String s) s
		helper1(table1.column("age").get(0))
		''').assertNoErrors
	}
}
