/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw.impl;

import etablesaw.xtext.xaw.InlineTableRow;
import etablesaw.xtext.xaw.XawPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XBlockExpressionImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inline Table Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InlineTableRowImpl extends XBlockExpressionImpl implements InlineTableRow
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InlineTableRowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XawPackage.Literals.INLINE_TABLE_ROW;
  }

} //InlineTableRowImpl
