/*
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XawProposalProvider extends AbstractXawProposalProvider {
}
