/*
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ide

import com.google.inject.Guice
import etablesaw.xtext.XawRuntimeModule
import etablesaw.xtext.XawStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XawIdeSetup extends XawStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XawRuntimeModule, new XawIdeModule))
	}
	
}
