/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inline Table Row</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see etablesaw.xtext.xaw.XawPackage#getInlineTableRow()
 * @model
 * @generated
 */
public interface InlineTableRow extends XBlockExpression
{
} // InlineTableRow
