/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link etablesaw.xtext.xaw.TableDef#getName <em>Name</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.TableDef#getTableColumDefs <em>Table Colum Defs</em>}</li>
 * </ul>
 *
 * @see etablesaw.xtext.xaw.XawPackage#getTableDef()
 * @model
 * @generated
 */
public interface TableDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see etablesaw.xtext.xaw.XawPackage#getTableDef_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.TableDef#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Table Colum Defs</b></em>' containment reference list.
   * The list contents are of type {@link etablesaw.xtext.xaw.TableColumnDef}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Table Colum Defs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Colum Defs</em>' containment reference list.
   * @see etablesaw.xtext.xaw.XawPackage#getTableDef_TableColumDefs()
   * @model containment="true"
   * @generated
   */
  EList<TableColumnDef> getTableColumDefs();

} // TableDef
