/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link etablesaw.xtext.xaw.TableColumn#getColumnDef <em>Column Def</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.TableColumn#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see etablesaw.xtext.xaw.XawPackage#getTableColumn()
 * @model
 * @generated
 */
public interface TableColumn extends XExpression
{
  /**
   * Returns the value of the '<em><b>Column Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Column Def</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Def</em>' containment reference.
   * @see #setColumnDef(TableColumnDef)
   * @see etablesaw.xtext.xaw.XawPackage#getTableColumn_ColumnDef()
   * @model containment="true"
   * @generated
   */
  TableColumnDef getColumnDef();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.TableColumn#getColumnDef <em>Column Def</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Def</em>' containment reference.
   * @see #getColumnDef()
   * @generated
   */
  void setColumnDef(TableColumnDef value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(XExpression)
   * @see etablesaw.xtext.xaw.XawPackage#getTableColumn_Expression()
   * @model containment="true"
   * @generated
   */
  XExpression getExpression();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.TableColumn#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(XExpression value);

} // TableColumn
