/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.xtext.xbase.XbasePackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see etablesaw.xtext.xaw.XawFactory
 * @model kind="package"
 * @generated
 */
public interface XawPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xaw";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "etablesaw/xtext/Xaw";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xaw";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XawPackage eINSTANCE = etablesaw.xtext.xaw.impl.XawPackageImpl.init();

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.TableDefImpl <em>Table Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.TableDefImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableDef()
   * @generated
   */
  int TABLE_DEF = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DEF__NAME = 0;

  /**
   * The feature id for the '<em><b>Table Colum Defs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DEF__TABLE_COLUM_DEFS = 1;

  /**
   * The number of structural features of the '<em>Table Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.TableColumnDefImpl <em>Table Column Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.TableColumnDefImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableColumnDef()
   * @generated
   */
  int TABLE_COLUMN_DEF = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN_DEF__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN_DEF__NAME = 1;

  /**
   * The number of structural features of the '<em>Table Column Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.XMethodImpl <em>XMethod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.XMethodImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXMethod()
   * @generated
   */
  int XMETHOD = 2;

  /**
   * The feature id for the '<em><b>Type Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__TYPE_PARAMETERS = 0;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__RETURN_TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__NAME = 2;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__PARAMETERS = 3;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD__BODY = 4;

  /**
   * The number of structural features of the '<em>XMethod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMETHOD_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.XawImpl <em>Xaw</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.XawImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXaw()
   * @generated
   */
  int XAW = 3;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int XAW__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__IMPORT_SECTION = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>QName</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__QNAME = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Table Defs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__TABLE_DEFS = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW__METHODS = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Xaw</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAW_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.TableLiteralImpl <em>Table Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.TableLiteralImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableLiteral()
   * @generated
   */
  int TABLE_LITERAL = 4;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int TABLE_LITERAL__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_LITERAL__NAME = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_LITERAL_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.TableColumnImpl <em>Table Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.TableColumnImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableColumn()
   * @generated
   */
  int TABLE_COLUMN = 5;

  /**
   * The feature id for the '<em><b>Column Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN__COLUMN_DEF = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN__EXPRESSION = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Table Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COLUMN_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.InlineTableRowImpl <em>Inline Table Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.InlineTableRowImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getInlineTableRow()
   * @generated
   */
  int INLINE_TABLE_ROW = 6;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @since 2.7
   * @generated
   * @ordered
   */
  int INLINE_TABLE_ROW__EXPRESSIONS = XbasePackage.XBLOCK_EXPRESSION__EXPRESSIONS;

  /**
   * The number of structural features of the '<em>Inline Table Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INLINE_TABLE_ROW_FEATURE_COUNT = XbasePackage.XBLOCK_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.TableRowLiteralImpl <em>Table Row Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.TableRowLiteralImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableRowLiteral()
   * @generated
   */
  int TABLE_ROW_LITERAL = 7;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW_LITERAL__EXPRESSIONS = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Row Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW_LITERAL_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.XLocalTimeLiteralImpl <em>XLocal Time Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.XLocalTimeLiteralImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXLocalTimeLiteral()
   * @generated
   */
  int XLOCAL_TIME_LITERAL = 8;

  /**
   * The feature id for the '<em><b>Hour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_TIME_LITERAL__HOUR = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_TIME_LITERAL__MIN = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Second</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_TIME_LITERAL__SECOND = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>XLocal Time Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_TIME_LITERAL_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.XLocalDateLiteralImpl <em>XLocal Date Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.XLocalDateLiteralImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXLocalDateLiteral()
   * @generated
   */
  int XLOCAL_DATE_LITERAL = 9;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_DATE_LITERAL__DAY = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_DATE_LITERAL__MONTH = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_DATE_LITERAL__YEAR = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>XLocal Date Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XLOCAL_DATE_LITERAL_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link etablesaw.xtext.xaw.impl.XURLLiteralImpl <em>XURL Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see etablesaw.xtext.xaw.impl.XURLLiteralImpl
   * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXURLLiteral()
   * @generated
   */
  int XURL_LITERAL = 10;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__URL = XbasePackage.XEXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Scheme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__SCHEME = XbasePackage.XEXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__HOST = XbasePackage.XEXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__PORT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__PATH = XbasePackage.XEXPRESSION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__PARAMS = XbasePackage.XEXPRESSION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Frag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL__FRAG = XbasePackage.XEXPRESSION_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>XURL Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XURL_LITERAL_FEATURE_COUNT = XbasePackage.XEXPRESSION_FEATURE_COUNT + 7;


  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.TableDef <em>Table Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Def</em>'.
   * @see etablesaw.xtext.xaw.TableDef
   * @generated
   */
  EClass getTableDef();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.TableDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see etablesaw.xtext.xaw.TableDef#getName()
   * @see #getTableDef()
   * @generated
   */
  EAttribute getTableDef_Name();

  /**
   * Returns the meta object for the containment reference list '{@link etablesaw.xtext.xaw.TableDef#getTableColumDefs <em>Table Colum Defs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Table Colum Defs</em>'.
   * @see etablesaw.xtext.xaw.TableDef#getTableColumDefs()
   * @see #getTableDef()
   * @generated
   */
  EReference getTableDef_TableColumDefs();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.TableColumnDef <em>Table Column Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Column Def</em>'.
   * @see etablesaw.xtext.xaw.TableColumnDef
   * @generated
   */
  EClass getTableColumnDef();

  /**
   * Returns the meta object for the containment reference '{@link etablesaw.xtext.xaw.TableColumnDef#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see etablesaw.xtext.xaw.TableColumnDef#getType()
   * @see #getTableColumnDef()
   * @generated
   */
  EReference getTableColumnDef_Type();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.TableColumnDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see etablesaw.xtext.xaw.TableColumnDef#getName()
   * @see #getTableColumnDef()
   * @generated
   */
  EAttribute getTableColumnDef_Name();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.XMethod <em>XMethod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XMethod</em>'.
   * @see etablesaw.xtext.xaw.XMethod
   * @generated
   */
  EClass getXMethod();

  /**
   * Returns the meta object for the containment reference list '{@link etablesaw.xtext.xaw.XMethod#getTypeParameters <em>Type Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Parameters</em>'.
   * @see etablesaw.xtext.xaw.XMethod#getTypeParameters()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_TypeParameters();

  /**
   * Returns the meta object for the containment reference '{@link etablesaw.xtext.xaw.XMethod#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see etablesaw.xtext.xaw.XMethod#getReturnType()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_ReturnType();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XMethod#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see etablesaw.xtext.xaw.XMethod#getName()
   * @see #getXMethod()
   * @generated
   */
  EAttribute getXMethod_Name();

  /**
   * Returns the meta object for the containment reference list '{@link etablesaw.xtext.xaw.XMethod#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see etablesaw.xtext.xaw.XMethod#getParameters()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link etablesaw.xtext.xaw.XMethod#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see etablesaw.xtext.xaw.XMethod#getBody()
   * @see #getXMethod()
   * @generated
   */
  EReference getXMethod_Body();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.Xaw <em>Xaw</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xaw</em>'.
   * @see etablesaw.xtext.xaw.Xaw
   * @generated
   */
  EClass getXaw();

  /**
   * Returns the meta object for the containment reference '{@link etablesaw.xtext.xaw.Xaw#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see etablesaw.xtext.xaw.Xaw#getImportSection()
   * @see #getXaw()
   * @generated
   */
  EReference getXaw_ImportSection();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.Xaw#getQName <em>QName</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>QName</em>'.
   * @see etablesaw.xtext.xaw.Xaw#getQName()
   * @see #getXaw()
   * @generated
   */
  EAttribute getXaw_QName();

  /**
   * Returns the meta object for the containment reference list '{@link etablesaw.xtext.xaw.Xaw#getTableDefs <em>Table Defs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Table Defs</em>'.
   * @see etablesaw.xtext.xaw.Xaw#getTableDefs()
   * @see #getXaw()
   * @generated
   */
  EReference getXaw_TableDefs();

  /**
   * Returns the meta object for the containment reference list '{@link etablesaw.xtext.xaw.Xaw#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methods</em>'.
   * @see etablesaw.xtext.xaw.Xaw#getMethods()
   * @see #getXaw()
   * @generated
   */
  EReference getXaw_Methods();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.TableLiteral <em>Table Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Literal</em>'.
   * @see etablesaw.xtext.xaw.TableLiteral
   * @generated
   */
  EClass getTableLiteral();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.TableLiteral#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see etablesaw.xtext.xaw.TableLiteral#getName()
   * @see #getTableLiteral()
   * @generated
   */
  EAttribute getTableLiteral_Name();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.TableColumn <em>Table Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Column</em>'.
   * @see etablesaw.xtext.xaw.TableColumn
   * @generated
   */
  EClass getTableColumn();

  /**
   * Returns the meta object for the containment reference '{@link etablesaw.xtext.xaw.TableColumn#getColumnDef <em>Column Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Column Def</em>'.
   * @see etablesaw.xtext.xaw.TableColumn#getColumnDef()
   * @see #getTableColumn()
   * @generated
   */
  EReference getTableColumn_ColumnDef();

  /**
   * Returns the meta object for the containment reference '{@link etablesaw.xtext.xaw.TableColumn#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see etablesaw.xtext.xaw.TableColumn#getExpression()
   * @see #getTableColumn()
   * @generated
   */
  EReference getTableColumn_Expression();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.InlineTableRow <em>Inline Table Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inline Table Row</em>'.
   * @see etablesaw.xtext.xaw.InlineTableRow
   * @generated
   */
  EClass getInlineTableRow();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.TableRowLiteral <em>Table Row Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Row Literal</em>'.
   * @see etablesaw.xtext.xaw.TableRowLiteral
   * @generated
   */
  EClass getTableRowLiteral();

  /**
   * Returns the meta object for the containment reference list '{@link etablesaw.xtext.xaw.TableRowLiteral#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see etablesaw.xtext.xaw.TableRowLiteral#getExpressions()
   * @see #getTableRowLiteral()
   * @generated
   */
  EReference getTableRowLiteral_Expressions();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.XLocalTimeLiteral <em>XLocal Time Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XLocal Time Literal</em>'.
   * @see etablesaw.xtext.xaw.XLocalTimeLiteral
   * @generated
   */
  EClass getXLocalTimeLiteral();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XLocalTimeLiteral#getHour <em>Hour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hour</em>'.
   * @see etablesaw.xtext.xaw.XLocalTimeLiteral#getHour()
   * @see #getXLocalTimeLiteral()
   * @generated
   */
  EAttribute getXLocalTimeLiteral_Hour();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XLocalTimeLiteral#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see etablesaw.xtext.xaw.XLocalTimeLiteral#getMin()
   * @see #getXLocalTimeLiteral()
   * @generated
   */
  EAttribute getXLocalTimeLiteral_Min();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XLocalTimeLiteral#getSecond <em>Second</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Second</em>'.
   * @see etablesaw.xtext.xaw.XLocalTimeLiteral#getSecond()
   * @see #getXLocalTimeLiteral()
   * @generated
   */
  EAttribute getXLocalTimeLiteral_Second();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.XLocalDateLiteral <em>XLocal Date Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XLocal Date Literal</em>'.
   * @see etablesaw.xtext.xaw.XLocalDateLiteral
   * @generated
   */
  EClass getXLocalDateLiteral();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XLocalDateLiteral#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see etablesaw.xtext.xaw.XLocalDateLiteral#getDay()
   * @see #getXLocalDateLiteral()
   * @generated
   */
  EAttribute getXLocalDateLiteral_Day();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XLocalDateLiteral#getMonth <em>Month</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Month</em>'.
   * @see etablesaw.xtext.xaw.XLocalDateLiteral#getMonth()
   * @see #getXLocalDateLiteral()
   * @generated
   */
  EAttribute getXLocalDateLiteral_Month();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XLocalDateLiteral#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see etablesaw.xtext.xaw.XLocalDateLiteral#getYear()
   * @see #getXLocalDateLiteral()
   * @generated
   */
  EAttribute getXLocalDateLiteral_Year();

  /**
   * Returns the meta object for class '{@link etablesaw.xtext.xaw.XURLLiteral <em>XURL Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XURL Literal</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral
   * @generated
   */
  EClass getXURLLiteral();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XURLLiteral#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getUrl()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Url();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XURLLiteral#getScheme <em>Scheme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scheme</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getScheme()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Scheme();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XURLLiteral#getHost <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Host</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getHost()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Host();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XURLLiteral#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getPort()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Port();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XURLLiteral#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getPath()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Path();

  /**
   * Returns the meta object for the attribute list '{@link etablesaw.xtext.xaw.XURLLiteral#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getParams()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Params();

  /**
   * Returns the meta object for the attribute '{@link etablesaw.xtext.xaw.XURLLiteral#getFrag <em>Frag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frag</em>'.
   * @see etablesaw.xtext.xaw.XURLLiteral#getFrag()
   * @see #getXURLLiteral()
   * @generated
   */
  EAttribute getXURLLiteral_Frag();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XawFactory getXawFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.TableDefImpl <em>Table Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.TableDefImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableDef()
     * @generated
     */
    EClass TABLE_DEF = eINSTANCE.getTableDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_DEF__NAME = eINSTANCE.getTableDef_Name();

    /**
     * The meta object literal for the '<em><b>Table Colum Defs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_DEF__TABLE_COLUM_DEFS = eINSTANCE.getTableDef_TableColumDefs();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.TableColumnDefImpl <em>Table Column Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.TableColumnDefImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableColumnDef()
     * @generated
     */
    EClass TABLE_COLUMN_DEF = eINSTANCE.getTableColumnDef();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_COLUMN_DEF__TYPE = eINSTANCE.getTableColumnDef_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_COLUMN_DEF__NAME = eINSTANCE.getTableColumnDef_Name();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.XMethodImpl <em>XMethod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.XMethodImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXMethod()
     * @generated
     */
    EClass XMETHOD = eINSTANCE.getXMethod();

    /**
     * The meta object literal for the '<em><b>Type Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__TYPE_PARAMETERS = eINSTANCE.getXMethod_TypeParameters();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__RETURN_TYPE = eINSTANCE.getXMethod_ReturnType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XMETHOD__NAME = eINSTANCE.getXMethod_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__PARAMETERS = eINSTANCE.getXMethod_Parameters();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMETHOD__BODY = eINSTANCE.getXMethod_Body();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.XawImpl <em>Xaw</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.XawImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXaw()
     * @generated
     */
    EClass XAW = eINSTANCE.getXaw();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XAW__IMPORT_SECTION = eINSTANCE.getXaw_ImportSection();

    /**
     * The meta object literal for the '<em><b>QName</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XAW__QNAME = eINSTANCE.getXaw_QName();

    /**
     * The meta object literal for the '<em><b>Table Defs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XAW__TABLE_DEFS = eINSTANCE.getXaw_TableDefs();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XAW__METHODS = eINSTANCE.getXaw_Methods();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.TableLiteralImpl <em>Table Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.TableLiteralImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableLiteral()
     * @generated
     */
    EClass TABLE_LITERAL = eINSTANCE.getTableLiteral();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_LITERAL__NAME = eINSTANCE.getTableLiteral_Name();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.TableColumnImpl <em>Table Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.TableColumnImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableColumn()
     * @generated
     */
    EClass TABLE_COLUMN = eINSTANCE.getTableColumn();

    /**
     * The meta object literal for the '<em><b>Column Def</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_COLUMN__COLUMN_DEF = eINSTANCE.getTableColumn_ColumnDef();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_COLUMN__EXPRESSION = eINSTANCE.getTableColumn_Expression();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.InlineTableRowImpl <em>Inline Table Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.InlineTableRowImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getInlineTableRow()
     * @generated
     */
    EClass INLINE_TABLE_ROW = eINSTANCE.getInlineTableRow();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.TableRowLiteralImpl <em>Table Row Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.TableRowLiteralImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getTableRowLiteral()
     * @generated
     */
    EClass TABLE_ROW_LITERAL = eINSTANCE.getTableRowLiteral();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_ROW_LITERAL__EXPRESSIONS = eINSTANCE.getTableRowLiteral_Expressions();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.XLocalTimeLiteralImpl <em>XLocal Time Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.XLocalTimeLiteralImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXLocalTimeLiteral()
     * @generated
     */
    EClass XLOCAL_TIME_LITERAL = eINSTANCE.getXLocalTimeLiteral();

    /**
     * The meta object literal for the '<em><b>Hour</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XLOCAL_TIME_LITERAL__HOUR = eINSTANCE.getXLocalTimeLiteral_Hour();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XLOCAL_TIME_LITERAL__MIN = eINSTANCE.getXLocalTimeLiteral_Min();

    /**
     * The meta object literal for the '<em><b>Second</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XLOCAL_TIME_LITERAL__SECOND = eINSTANCE.getXLocalTimeLiteral_Second();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.XLocalDateLiteralImpl <em>XLocal Date Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.XLocalDateLiteralImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXLocalDateLiteral()
     * @generated
     */
    EClass XLOCAL_DATE_LITERAL = eINSTANCE.getXLocalDateLiteral();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XLOCAL_DATE_LITERAL__DAY = eINSTANCE.getXLocalDateLiteral_Day();

    /**
     * The meta object literal for the '<em><b>Month</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XLOCAL_DATE_LITERAL__MONTH = eINSTANCE.getXLocalDateLiteral_Month();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XLOCAL_DATE_LITERAL__YEAR = eINSTANCE.getXLocalDateLiteral_Year();

    /**
     * The meta object literal for the '{@link etablesaw.xtext.xaw.impl.XURLLiteralImpl <em>XURL Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see etablesaw.xtext.xaw.impl.XURLLiteralImpl
     * @see etablesaw.xtext.xaw.impl.XawPackageImpl#getXURLLiteral()
     * @generated
     */
    EClass XURL_LITERAL = eINSTANCE.getXURLLiteral();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__URL = eINSTANCE.getXURLLiteral_Url();

    /**
     * The meta object literal for the '<em><b>Scheme</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__SCHEME = eINSTANCE.getXURLLiteral_Scheme();

    /**
     * The meta object literal for the '<em><b>Host</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__HOST = eINSTANCE.getXURLLiteral_Host();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__PORT = eINSTANCE.getXURLLiteral_Port();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__PATH = eINSTANCE.getXURLLiteral_Path();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__PARAMS = eINSTANCE.getXURLLiteral_Params();

    /**
     * The meta object literal for the '<em><b>Frag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XURL_LITERAL__FRAG = eINSTANCE.getXURLLiteral_Frag();

  }

} //XawPackage
