/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XLocal Date Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link etablesaw.xtext.xaw.XLocalDateLiteral#getDay <em>Day</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XLocalDateLiteral#getMonth <em>Month</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XLocalDateLiteral#getYear <em>Year</em>}</li>
 * </ul>
 *
 * @see etablesaw.xtext.xaw.XawPackage#getXLocalDateLiteral()
 * @model
 * @generated
 */
public interface XLocalDateLiteral extends XExpression
{
  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Day</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see #setDay(int)
   * @see etablesaw.xtext.xaw.XawPackage#getXLocalDateLiteral_Day()
   * @model
   * @generated
   */
  int getDay();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XLocalDateLiteral#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see #getDay()
   * @generated
   */
  void setDay(int value);

  /**
   * Returns the value of the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Month</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Month</em>' attribute.
   * @see #setMonth(String)
   * @see etablesaw.xtext.xaw.XawPackage#getXLocalDateLiteral_Month()
   * @model
   * @generated
   */
  String getMonth();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XLocalDateLiteral#getMonth <em>Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Month</em>' attribute.
   * @see #getMonth()
   * @generated
   */
  void setMonth(String value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Year</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see etablesaw.xtext.xaw.XawPackage#getXLocalDateLiteral_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XLocalDateLiteral#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

} // XLocalDateLiteral
