/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.xtext.common.types.JvmIdentifiableElement;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XUnary Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link etablesaw.xtext.xaw.XUnaryOperation#getFeature <em>Feature</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XUnaryOperation#getOperand <em>Operand</em>}</li>
 * </ul>
 *
 * @see etablesaw.xtext.xaw.XawPackage#getXUnaryOperation()
 * @model
 * @generated
 */
public interface XUnaryOperation extends XExpression
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' reference.
   * @see #setFeature(JvmIdentifiableElement)
   * @see etablesaw.xtext.xaw.XawPackage#getXUnaryOperation_Feature()
   * @model
   * @generated
   */
  JvmIdentifiableElement getFeature();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XUnaryOperation#getFeature <em>Feature</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(JvmIdentifiableElement value);

  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operand</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference.
   * @see #setOperand(XExpression)
   * @see etablesaw.xtext.xaw.XawPackage#getXUnaryOperation_Operand()
   * @model containment="true"
   * @generated
   */
  XExpression getOperand();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XUnaryOperation#getOperand <em>Operand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand</em>' containment reference.
   * @see #getOperand()
   * @generated
   */
  void setOperand(XExpression value);

} // XUnaryOperation
