/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.xaw;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XURL Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getUrl <em>Url</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getScheme <em>Scheme</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getHost <em>Host</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getPort <em>Port</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getPath <em>Path</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getParams <em>Params</em>}</li>
 *   <li>{@link etablesaw.xtext.xaw.XURLLiteral#getFrag <em>Frag</em>}</li>
 * </ul>
 *
 * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral()
 * @model
 * @generated
 */
public interface XURLLiteral extends XExpression
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XURLLiteral#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Scheme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scheme</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scheme</em>' attribute.
   * @see #setScheme(String)
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Scheme()
   * @model
   * @generated
   */
  String getScheme();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XURLLiteral#getScheme <em>Scheme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scheme</em>' attribute.
   * @see #getScheme()
   * @generated
   */
  void setScheme(String value);

  /**
   * Returns the value of the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Host</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Host</em>' attribute.
   * @see #setHost(String)
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Host()
   * @model
   * @generated
   */
  String getHost();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XURLLiteral#getHost <em>Host</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Host</em>' attribute.
   * @see #getHost()
   * @generated
   */
  void setHost(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XURLLiteral#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XURLLiteral#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' attribute list.
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Params()
   * @model unique="false"
   * @generated
   */
  EList<String> getParams();

  /**
   * Returns the value of the '<em><b>Frag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Frag</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frag</em>' attribute.
   * @see #setFrag(String)
   * @see etablesaw.xtext.xaw.XawPackage#getXURLLiteral_Frag()
   * @model
   * @generated
   */
  String getFrag();

  /**
   * Sets the value of the '{@link etablesaw.xtext.xaw.XURLLiteral#getFrag <em>Frag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frag</em>' attribute.
   * @see #getFrag()
   * @generated
   */
  void setFrag(String value);

} // XURLLiteral
