/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import etablesaw.xtext.XawRuntimeModule;
import etablesaw.xtext.XawStandaloneSetup;
import etablesaw.xtext.ide.XawIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XawIdeSetup extends XawStandaloneSetup {
  @Override
  public Injector createInjector() {
    XawRuntimeModule _xawRuntimeModule = new XawRuntimeModule();
    XawIdeModule _xawIdeModule = new XawIdeModule();
    return Guice.createInjector(Modules2.mixin(_xawRuntimeModule, _xawIdeModule));
  }
}
