/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ide;

import etablesaw.xtext.ide.AbstractXawIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XawIdeModule extends AbstractXawIdeModule {
}
