/**
 * generated by Xtext 2.14.0
 */
package etablesaw.xtext.ui;

import etablesaw.xtext.ui.AbstractXawUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XawUiModule extends AbstractXawUiModule {
  public XawUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
